Added Makefile
iver-wharf/wharf-provider-github pull request #24
Opened 2021-07-19 11:16 UTC by jilleJr

- \[ ] I've added a new note in the `CHANGELOG.md` file, according to docs:
  https://iver-wharf.github.io/#/development/changelogs/writing-changelogs

## Summary

- Added a Makefile, used by GNU Make that comes shipped with virtually every GNU/Linux distro out there.
- Updated README.md to use GNU Make instead of the commands directly.

## Motivation

This will simplify things so we just keep track of having to do `make swag` instead of all the `--parseDependency --parseDepth` stuff.

Also, some of the `Dockerfile` changes makes it so the build uses the Docker cache more efficiently, leading to faster consequitive builds.

2021-07-19 11:29 UTC, Alexamakans requested changes

2021-07-19 11:29 UTC, Alexamakans commented on Makefile
> +	swag init --parseDependency --parseDepth 1
As #16 has been merged, `--parseDepth 2` is required
```suggestion
	swag init --parseDependency --parseDepth 2
```

2021-07-19 14:34 UTC, Alexamakans commented on Makefile
> +	swag init --parseDependency --parseDepth 1
This doesn't seem to be resolved, or am I missing something?

2021-08-17 12:37 UTC, fredx30 approved these changes

2021-08-17 12:37 UTC, fredx30 commented on Dockerfile
> +    authoritative-source-url="quay.io"
I think this could deserve a comment. Maybe add in the source?
```suggestion
# The added labels are based on this: https://github.com/projectatomic/ContainerApplicationGenericLabels
LABEL name="iver-wharf/wharf-provider-github" \
    url="https://github.com/iver-wharf/wharf-provider-github" \
    release=${BUILD_REF} \
    build-date=${BUILD_DATE} \
    vendor="Iver" \
    version=${BUILD_VERSION} \
    vcs-type="git" \
    vcs-url="https://github.com/iver-wharf/wharf-provider-github" \
    vcs-ref=${BUILD_GIT_COMMIT} \
    changelog-url="https://github.com/iver-wharf/wharf-provider-github/blob/${BUILD_VERSION}/CHANGELOG.md" \
    authoritative-source-url="quay.io"
```

2021-08-17 12:40 UTC, jilleJr commented on Dockerfile
> +    authoritative-source-url="quay.io"
Good idea!

2021-08-18 07:20 UTC, iverestefans approved these changes
LGTM!

2021-08-18 10:05 UTC, Alexamakans approved these changes

2021-08-18 10:05 UTC, merged