Add early return on project refresh for /import/github.
iver-wharf/wharf-provider-github pull request #52
Opened 2022-05-11 12:09 UTC by fredx30

This resolves and issue describe in https://github.com/iver-wharf/wharf-provider-github/issues/51

A post type request body targeting `/import/github` with contents 
```json
{"projectId":2,"url":"https://api.github.com","tokenId":1,"group":"iver-wharf","project":"wharf-api","providerId":1}
```  
Would cause a project refresh to succeed with a failiure message. When the project would get refreshed in [the first if](https://github.com/iver-wharf/wharf-provider-github/blob/bba1216605d232f60d6d5eb91741a232a16d60df/github.go#L87-L113) and would then return a failiure on the create new project condition. This error would get passed forward to the web client.

2022-05-11 12:15 UTC, jilleJr requested changes
I do unironically love it when the description is longer than the fix.

Missing CHANGELOG.md changes, otherwise it's super-nice!

2022-05-11 17:40 UTC, fredx30 commented
> I do unironically love it when the description is longer than the fix.
> 
> Missing CHANGELOG.md changes, otherwise it's super-nice!

Added the feature template to this PR & added a changelog entry.

2022-05-12 05:37 UTC, jilleJr approved these changes
Small change in the CHANGELOG.md, otherwise LGTM!

2022-05-12 05:37 UTC, jilleJr commented on CHANGELOG.md
> +  an error. (#51)
Should be the PR reference and not the issue reference

```suggestion
  an error. (#52)
```

2022-05-12 05:51 UTC, jilleJr commented
Also, suggest changing the PR description so it says "Closes #51"

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2022-05-12 09:26 UTC, Alexamakans approved these changes
Nice 👍🏻

2022-05-12 13:40 UTC, merged